gateways:
  mysql:
    connection:
      type: mysql
      host: {{ env_var('MYSQL_HOST') }}
      port: {{ env_var('MYSQL_TCP_PORT') }}
      user: {{ env_var('MYSQL_USER') }}
      password: {{ env_var('MYSQL_PWD') }}
  duckdb:
    connection:
      type: duckdb
      database: duckdb.db

default_gateway: mysql
gateway_managed_virtual_layer: true

model_defaults:
  dialect: mysql
  start: 2025-10-02

variables:
  super_admin_id: 1
  time_zone: '+00:00'
  pt_br_templates:
    - 1577024021
    - 1316548433
    - 1709021214
    - 639302930
    - 1709119945
    - 1574045256
    - 1704331608
    - 299352315
    - 1966612522
