gateways:
  mysql:
    connection:
      type: mysql
      charset: utf8mb4
      host: {{ env_var('MYSQL_HOST') }}
      port: {{ env_var('MYSQL_TCP_PORT') }}
      user: {{ env_var('MYSQL_USER') }}
      password: {{ env_var('MYSQL_PWD') }}

    test_connection:
      type: mysql
      charset: utf8mb4
      host: {{ env_var('MYSQL_HOST') }}
      port: {{ env_var('MYSQL_TCP_PORT') }}
      user: {{ env_var('MYSQL_USER') }}
      password: {{ env_var('MYSQL_PWD') }}
      database: "sqlmesh_unit_tests"

  duckdb:
    connection:
      type: duckdb
      database: duckdb.db

default_gateway: mysql
gateway_managed_virtual_layer: true

model_defaults:
  dialect: mysql
  start: 2025-10-02

variables:
  time_zone: '+00:00'
  start_ds: '2000-01-01'
  end_ds: '2026-12-31'
