# --- Gateway Connection ---
gateways:
  source:
    connection:
      # For more information on configuring the connection to your execution engine, visit:
      # https://sqlmesh.readthedocs.io/en/stable/reference/configuration/#connection
      # https://sqlmesh.readthedocs.io/en/stable/integrations/engines/mysql/#connection-options
      type: mysql
      charset: utf8mb4
      host: {{ env_var('SOURCE_DB_HOST') }}
      port: {{ env_var('SOURCE_DB_PORT') }}
      user: {{ env_var('SOURCE_DB_USER') }}
      password: {{ env_var('SOURCE_DB_PASSWORD') }}
      database: {{ env_var('SOURCE_DB_NAME') }}
      ssl_disabled: true

  target:
    connection:
      type: mysql
      charset: utf8mb4
      host: {{ env_var('TARGET_DB_HOST') }}
      port: {{ env_var('TARGET_DB_PORT') }}
      user: {{ env_var('TARGET_DB_USER') }}
      password: {{ env_var('TARGET_DB_PASSWORD') }}
      database: {{ env_var('TARGET_DB_NAME') }}
      ssl_disabled: true

default_gateway: mysql

# --- Model Defaults ---
# https://sqlmesh.readthedocs.io/en/stable/reference/model_configuration/#model-defaults

model_defaults:
  dialect: mysql
  start: 2025-10-05 # Start date for backfill history
  cron: '@weekly'    # Run models daily at 12am UTC (can override per model)

# --- Linting Rules ---
# Enforce standards for your team
# https://sqlmesh.readthedocs.io/en/stable/guides/linter/

linter:
  enabled: true
  rules:
    - ambiguousorinvalidcolumn
    - invalidselectstarexpansion
    - noambiguousprojections
