# --- Gateway Connection ---
gateways:
  mysql:
    connection:
      # For more information on configuring the connection to your execution engine, visit:
      # https://sqlmesh.readthedocs.io/en/stable/reference/configuration/#connection
      # https://sqlmesh.readthedocs.io/en/stable/integrations/engines/mysql/#connection-options
      type: mysql
      host: 
      user: 
      password: 
      # concurrent_tasks: 4
      # register_comments: True
      # pre_ping: True
      # pretty_sql: False
      # schema_differ_overrides: 
      # catalog_type_overrides: 
      # port: 
      # database: 
      # charset: 
      # collation: 
      # ssl_disabled: 

default_gateway: mysql

# --- Model Defaults ---
# https://sqlmesh.readthedocs.io/en/stable/reference/model_configuration/#model-defaults

model_defaults:
  dialect: mysql
  start: 2025-10-05 # Start date for backfill history
  cron: '@daily'    # Run models daily at 12am UTC (can override per model)

# --- Linting Rules ---
# Enforce standards for your team
# https://sqlmesh.readthedocs.io/en/stable/guides/linter/

linter:
  enabled: true
  rules:
    - ambiguousorinvalidcolumn
    - invalidselectstarexpansion
    - noambiguousprojections
